DROP TABLE IF EXISTS snowflakes;

CREATE TABLE snowflakes(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
	name VARCHAR,
	safespace VARCHAR,
	genderself FLOAT,
	date DATE
);

INSERT INTO snowflakes (name, safespace, genderself, date)
VALUES
	('Flippity Floppity', 'my room', 68.9, '1999-12-31'),
	('Reginald Butterworth', 'onlyFans', 1.8, '2000-11-11')
;
